import numpy as np
from ROM import ROM_NN_Methods

# Load PODNN model generated by main.py
podnn_model_path = "./Export/Models/podnn_model.pkl"
podnn_model = ROM_NN_Methods.load_podnn_model(podnn_model_path)

podnn_data = podnn_model["podnn_data"]
reduced_data = podnn_model["reduced_data"]
metadata = podnn_model["metadata"]

print("[Online] Loaded PODNN model")
print(f"[Online] metadata={metadata}")
print(f"[Online] V shape={reduced_data['V'].shape}")
print(f"[Online] PODNN hidden layers={podnn_data['hidden_layers']}")
print(f"[Online] PODNN coefficient training error={podnn_data['train_error_coefficients']:.3e}")
print("-" * 100)


# Rebuild PODNN object only with the data needed online
podnn = ROM_NN_Methods(
    reduced_data=reduced_data,
    training_set=None,
    fom_data=None
)


# Choose new online parameter
mu0 = 5.0
mu1 = 4.0

print("\n[Online] Solving PODNN ROM")
print(f"[Online] mu0={mu0}, mu1={mu1}")

podnn_sol = podnn.solve_PODNN(
    mu0=mu0,
    mu1=mu1,
    podnn_data=podnn_data,
    plot_solution=False
)

print("\n[Online] Completed")
print(f"[Online] converged={podnn_sol['converged']}")
print(f"[Online] iterations={podnn_sol['iterations']}")
print(f"[Online] relative_increment={podnn_sol['relative_increment']:.3e}")
print(f"[Online] coefficients shape={podnn_sol['coefficients'].shape}")
print(f"[Online] reconstructed solution shape={podnn_sol['u'].shape}")


# Split reconstructed PODNN solution
speed_n_dofs = reduced_data["speed_n_dofs"]

u_podnn = podnn_sol["u"]
u_x_podnn = u_podnn[0:speed_n_dofs]
u_y_podnn = u_podnn[speed_n_dofs:2 * speed_n_dofs]
p_podnn = u_podnn[2 * speed_n_dofs:]

print("\n[Online] Solution components")
print(f"u_x_podnn shape={u_x_podnn.shape}")
print(f"u_y_podnn shape={u_y_podnn.shape}")
print(f"p_podnn shape={p_podnn.shape}")
print()
print("=" * 100)