import numpy as np

from PINN import PINN_Methods


# Load PINN model generated by main.py
pinn_model_path = "./Export/Models/pinn_model.pkl"
pinn_model_data = PINN_Methods.load_PINN_model(pinn_model_path)

mu0_range = pinn_model_data["mu0_range"]
mu1_range = pinn_model_data["mu1_range"]
metadata = pinn_model_data["metadata"]

print("[Online] Loaded PINN model")
print(f"[Online] metadata={metadata}")
print(f"[Online] mu0_range={mu0_range}")
print(f"[Online] mu1_range={mu1_range}")
print("-" * 100)


# Rebuild PINN object only with the data needed online
pinn = PINN_Methods(
    mu0_range=mu0_range,
    mu1_range=mu1_range,
    fom_data=None
)


# Rebuild the same neural architecture used offline
pinn_model = pinn.build_network(
    width=metadata["width"],
    latent_dim=metadata["latent_dim"],
    n_residual_blocks=metadata["n_residual_blocks"]
)
pinn_model.load_state_dict(pinn_model_data["model_state_dict"])
pinn_model.eval()


# Choose new online parameter
mu0 = 1.0
mu1 = 3.0

# Choose a regular grid for pure online evaluation
n_grid = 80
x_grid = np.linspace(0.0, 1.0, n_grid)
y_grid = np.linspace(0.0, 1.0, n_grid)
X, Y = np.meshgrid(x_grid, y_grid)

x_eval = X.ravel()
y_eval = Y.ravel()

print("\n[Online] Solving PINN")
print(f"[Online] mu0={mu0}, mu1={mu1}")
print(f"[Online] grid shape={X.shape}")

pinn_sol = pinn.solve_PINN(
    model=pinn_model,
    x=x_eval,
    y=y_eval,
    mu0=mu0,
    mu1=mu1,
    plot_solution=False
)

print("\n[Online] Completed")
print(f"[Online] converged={pinn_sol['converged']}")
print(f"[Online] iterations={pinn_sol['iterations']}")
print(f"[Online] relative_increment={pinn_sol['relative_increment']}")
print(f"[Online] reconstructed solution shape={pinn_sol['u'].shape}")


# Split reconstructed PINN solution
u_x_pinn = pinn_sol["u_x"]
u_y_pinn = pinn_sol["u_y"]
p_pinn = pinn_sol["p"]

u_mag_pinn = np.sqrt(u_x_pinn**2 + u_y_pinn**2)

print("\n[Online] Solution components")
print(f"u_x_pinn shape={u_x_pinn.shape}")
print(f"u_y_pinn shape={u_y_pinn.shape}")
print(f"p_pinn shape={p_pinn.shape}")
print(f"u_mag_pinn shape={u_mag_pinn.shape}")
print()
print("=" * 100)